version: '3'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "80:3000"
    links:
      - db
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
